config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'bookmarks#index'
  resources :lists, only: %i[index new create show]
  resources :movies, only: %i[index new create show]
  resources :bookmarks, except: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, length: { minimum: 6 }
  validates :movie, uniqueness: { scope: :list }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks
  # has_many through is needed because it's through a joint table we delete it
  has_many :movies, through: :bookmarks, dependent: :destroy

  validates :name, presence: true
  validates_uniqueness_of :name
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks

  validates_uniqueness_of :title
  validates :title, presence: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_bookmark, only: %w[show edit update destroy]

  def index
    @bookmarks = Bookmark.all
  end

  def show
  end

  def new
    @bookmark = Bookmark.new
    @movies = Movie.all
    @lists = List.all
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)

    if @bookmark.save
      redirect_to @bookmark
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @bookmark.update(bookmark_params)
      redirect_to @bookmark
    else
      render :edit
    end
  end

  def destroy
    @bookmark.destroy
    redirect_to bookmarks_path # not sure
  end

  private

  def set_bookmark
    @bookmark = Bookmark.find(params[:id])
  end

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id, :list_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: %w[show]

  def index
    @lists = List.all
  end

  def show
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)

    if @list.save
      redirect_to @list
    else
      render :new
    end
  end

  private

  def set_list
    @list = List.find(params[:id])
  end

  def list_params
    params.require(:list).permit(:name)
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: %w[show]

  def index
    @movies = Movie.all
  end

  def show
  end

  def new
    @movie = Movie.new
  end

  def create
    @movie = Movie.new(movie_params)

    if @movie.save
      redirect_to @movie
    else
      render :new
    end
  end

  private

  def set_movie
    @movie = Movie.find(params[:id])
  end

  def movie_params
    params.require(:movie).permit(:title, :overview, :poster_url, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/bookmarks/edit.html.erb
<h1>File path: (bookmarks) new.html.erb</h1>
<h2>Update a new bookmark</h2>
<%= simple_form_for @bookmark do |f| %>
  <%= f.input :comment %>
  <%= f.association :movie, collection: @movies %>
  <%= f.association :list, collection: @lists %>
  <%= f.submit %>
<% end %>

<br>
<%= link_to 'Back', bookmarks_path %>

app/views/bookmarks/index.html.erb
<nav class="navbar navbar-dark bg-dark justify-content-end">
  <%= link_to 'New Bookmark', new_bookmark_path, class: "btn btn-light" %>

</nav>

<div class="banner">
  <h1>File path: (bookmarks) index.html.erb</h1>
  <h2>All bookmarks</h2>
</div>


<table>
  <thead>
    <tr>
      <th>id</th>
      <th>Comment</th>
      <th>Movie</th>
      <th>List</th>
    </tr>
  </thead>

  <tbody>
    <% @bookmarks.each do |bookmark| %>
      <tr>
        <td><%= bookmark.id %></td>
        <td><%= bookmark.comment %></td>
        <td><%= bookmark.movie.title %></td>
        <td><%= bookmark.list.name %></td>
        <td><%= link_to 'Show', bookmark, class: "btn btn-primary" %></td>
        <td><%= link_to 'Edit', edit_bookmark_path(bookmark), class: "btn btn-primary" %></td>
        <td><%= link_to 'Delete', bookmark_path(bookmark), method: :delete, class: "btn btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/bookmarks/new.html.erb
<h1>File path: (bookmarks) new.html.erb</h1>
<h2>Create a new bookmark</h2>
<%= simple_form_for @bookmark do |f| %>
  <%= f.input :comment %>
  <%= f.association :movie, collection: @movies %>
  <%= f.association :list, collection: @lists %>
  <%= f.submit %>
<% end %>

<br>
<%= link_to 'Back', root_path %>

app/views/bookmarks/show.html.erb
<h1>File path: (bookmarks) Show.html.erb</h1>
<h2>Bookmark detail</h2>
<br>

<p>
  <strong>Bookmark comment:</strong>
  <%= @bookmark.comment %>
</p>
<br>

<p>
  <strong>Bookmark movie id:</strong>
  <%= @bookmark.movie_id %>
</p>
<br>

<p>
  <strong>Bookmark list id:</strong>
  <%= @bookmark.list_id %>
</p>
<br>

<%= link_to 'Back', root_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<h1>File path: (lists) index.html.erb</h1>
<h2>All lists</h2>

<table>
  <thead>
    <tr>
      <th>id</th>
      <th>name</th>
    </tr>
  </thead>

  <tbody>
    <% @lists.each do |list| %>
      <tr>
        <td><%= list.id %></td>
        <td><%= list.name %></td>
        <td><%= link_to 'Show', list %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New List', new_list_path %>

app/views/lists/new.html.erb
<h1>File path: (lists) new.html.erb</h1>
<h2>Create a new list</h2>
<%= simple_form_for @list do |f| %>
  <%= f.input :name %>
  <%= f.submit %>
<% end %>

<br>
<%= link_to 'Back', lists_path %>

app/views/lists/show.html.erb
<h1>File path: (lists) Show.html.erb</h1>
<h2>List detail</h2>
<br>

<p>
  <strong>List Name:</strong>
  <%= @list.name %>
</p>
<br>

<%= link_to 'Back', lists_path %>

app/views/movies/index.html.erb
<h1>File path: (movies) index.html.erb</h1>
<h2>All movies</h2>

<table>
  <thead>
    <tr>
      <th>id</th>
      <th>title</th>
      <th>rating</th>
    </tr>
  </thead>

  <tbody>
    <% @movies.each do |movie| %>
      <tr>
        <td><%= movie.id %></td>
        <td><%= movie.title %></td>
        <td><%= movie.rating %></td>
        <td><%= link_to 'Show', movie %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Movie', new_movie_path %>

app/views/movies/new.html.erb
<h1>File path: (movies) new.html.erb</h1>
<h2>Create a new movie</h2>
<%= simple_form_for @movie do |f| %>
  <%= f.input :title %>
  <%= f.input :overview %>
  <%= f.input :poster_url %>
  <%= f.input :rating %>
  <%= f.submit %>
<% end %>

<br>
<%= link_to 'Back', movies_path %>

app/views/movies/show.html.erb
<h1>File path: (movies) show.html.erb</h1>
<h2>Movie detail</h2>
<br>

<p>
  <strong>Movie title:</strong>
  <%= @movie.title %>
</p>
<p>
  <strong>Movie overview:</strong>
  <%= @movie.overview %>
</p>
<p>
  <strong>Movie poster URL:</strong>
  <%= @movie.poster_url %>
</p>
<p>
  <strong>Movie rating:</strong>
  <%= @movie.rating %>
</p>
<br>

<%= link_to 'Back', movies_path %>